name: Ruff
on: 
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Ruff
        run: |
          make ruff
      # - uses: chartboost/ruff-action@v1
      #   with:
      #     args: --check src/
      #     fix_args: --fix src/
      #     #args: --format src/
      #     config: ruff.toml